from typing import Protocol, Optional, Iterator
from uuid import UUID
from domain.market_listing import MarketListing

class IMarketListingRepository(Protocol):

    def save(self, listing: MarketListing) -> None: ...

    def find_by_id(self, listing_id: UUID) -> Optional[MarketListing]: ...

    def find_by_producer_id(self, producer_id: UUID) -> list[MarketListing]: ...

    def find_active(self, page: int, page_size: int) -> list[MarketListing]: ...

    def find_all_active(self) -> list[MarketListing]: ...

    def deactivate(self, listing_id: UUID) -> None: ...

    def transaction(self) -> Iterator[None]: ...
