from typing import Protocol, Optional, Iterator
from uuid import UUID
from domain.market_listing import MarketListing
import datetime

class IMarketListingRepository(Protocol):

    def save(self, listing: MarketListing) -> None: ...

    def find_by_id(self, listing_id: UUID) -> Optional[MarketListing]: ...

    def find_by_producer_id(self, producer_id: UUID) -> list[MarketListing]: ...

    def find_active(self, limit: int, created_at: Optional[datetime.datetime], listing_id: Optional[UUID]) -> list[MarketListing]: ...

    def find_all_active(self) -> list[MarketListing]: ...

    def deactivate(self, listing_id: UUID) -> None: ...

    def transaction(self) -> Iterator[None]: ...
