from enum import Enum

class SensorType(Enum):
    # Crop / soil sensors
    SOIL_MOISTURE = "SOIL_MOISTURE"
    SOIL_PH = "SOIL_PH"
    SOIL_TEMPERATURE = "SOIL_TEMPERATURE"
    LIGHT_INTENSITY = "LIGHT_INTENSITY"
    WATER_LEVEL = "WATER_LEVEL"

    # Cattle sensors
    CATTLE_BODY_TEMP = "CATTLE_BODY_TEMP"
    CATTLE_ACTIVITY_LEVEL = "CATTLE_ACTIVITY_LEVEL"
    CATTLE_MILK_YIELD = "CATTLE_MILK_YIELD"

    # Poultry sensors
    POULTRY_COOP_TEMP = "POULTRY_COOP_TEMP"
    POULTRY_CO2_PPM = "POULTRY_CO2_PPM"
    POULTRY_HUMIDITY = "POULTRY_HUMIDITY"

    # Fisherman / aquaculture sensors
    WATER_DISSOLVED_OXYGEN = "WATER_DISSOLVED_OXYGEN"
    WATER_SALINITY = "WATER_SALINITY"
    WATER_TEMPERATURE = "WATER_TEMPERATURE"
